
-- Create microblog table
DROP TABLE IF EXISTS micro_posts;
CREATE TABLE micro_posts(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, body TEXT, author_id INTEGER, snippet_id INTEGER, tag_id INTEGER NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- Create authors table
DROP TABLE IF EXISTS authors;
CREATE TABLE  authors(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, email TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);


-- Create snippets table
DROP TABLE IF EXISTS snippets;
CREATE TABLE snippets(id INTEGER PRIMARY KEY AUTOINCREMENT, body TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- Create tags table
DROP TABLE IF EXISTS tags;
CREATE TABLE tags(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, author_id INTEGER, TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

